name: Deploy to ECS

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: quasarcelestio/test-bk
  ECS_SERVICE: quasar-service
  ECS_CLUSTER: quasar-cluster

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      working-directory: ./backend
      run: |
        docker build -t ${{ env.ECR_REPOSITORY }}:${{ github.sha }} .
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}
        format: 'json'
        output: 'trivy-results.json'

    - name: Push Trivy scan results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-results
        path: trivy-results.json

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image to Docker Hub
      run: docker push ${{ env.ECR_REPOSITORY }}:${{ github.sha }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      
    - name: Terraform Init
      working-directory: ./tf-ecs
      run: terraform init
      
    - name: Terraform Apply
      working-directory: ./tf-ecs
      run: |
        export TF_VAR_pg_user=${{ secrets.PG_USER }}
        export TF_VAR_pg_host=${{ secrets.PG_HOST }}
        export TF_VAR_pg_database=${{ secrets.PG_DATABASE }}
        export TF_VAR_pg_password=${{ secrets.PG_PASSWORD }}
        export TF_VAR_pg_port=${{ secrets.PG_PORT }}
        export TF_VAR_tag=${{ github.sha }}
        terraform apply -auto-approve